spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/securivault
      username: securivault
      password: securivault
      driver-class-name: org.postgresql.Driver
logging:
  file:
    name: '/.logs/securivault.log'
  level:
    root: error
    com.xlf: debug
    com.xlf.mappers: info