spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ExampleDatabase
    username: ExampleUsername
    password: ExamplePassword
    driver-class-name: org.postgresql.Driver
  mail:
    default-encoding: utf-8
    host: smtp.example.com
    username: noreplay@example.com
    password: "ExamplePassword"
logging:
  file:
    path: .logs/
  level:
    root: error
    com.xlf.securivault: debug
    com.xlf.securivault.mappers: info