spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/securivault
      username: securivault
      password: securivault
      driver-class-name: org.postgresql.Driver
logging:
  file:
    path: .logs/
  level:
    root: error
    com.xlf.securivault: debug
    com.xlf.securivault.mappers: info